namespace Dox_Tool_V2
{
	// Token: 0x02000009 RID: 9
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x0600002B RID: 43 RVA: 0x000040FC File Offset: 0x000022FC
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600002C RID: 44 RVA: 0x0000413C File Offset: 0x0000233C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Dox_Tool_V2.Form1));
			this.personSearch = new global::System.ComponentModel.BackgroundWorker();
			this.emailWorker = new global::System.ComponentModel.BackgroundWorker();
			this.googleWorker = new global::System.ComponentModel.BackgroundWorker();
			this.LogInThemeContainer1 = new global::Dox_Tool_V2.LogInThemeContainer();
			this.LogInTabControl1 = new global::Dox_Tool_V2.LogInTabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.LogInLabel16 = new global::Dox_Tool_V2.LogInLabel();
			this.personProgress = new global::Dox_Tool_V2.LogInProgressBar();
			this.personSearchResults = new global::System.Windows.Forms.ListBox();
			this.nameSearch = new global::Dox_Tool_V2.LogInButton();
			this.location = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel3 = new global::Dox_Tool_V2.LogInLabel();
			this.lastName = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.firstName = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel2 = new global::Dox_Tool_V2.LogInLabel();
			this.LogInLabel1 = new global::Dox_Tool_V2.LogInLabel();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.LogInLabel17 = new global::Dox_Tool_V2.LogInLabel();
			this.emailProgress = new global::Dox_Tool_V2.LogInProgressBar();
			this.emailSearchResults = new global::System.Windows.Forms.ListBox();
			this.emailSearch = new global::Dox_Tool_V2.LogInButton();
			this.email = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel4 = new global::Dox_Tool_V2.LogInLabel();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.LogInLabel18 = new global::Dox_Tool_V2.LogInLabel();
			this.usernameProgress = new global::Dox_Tool_V2.LogInProgressBar();
			this.usernameSearchResults = new global::System.Windows.Forms.ListBox();
			this.userSearch = new global::Dox_Tool_V2.LogInButton();
			this.usernameSearch = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel5 = new global::Dox_Tool_V2.LogInLabel();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.LogInGroupBox2 = new global::Dox_Tool_V2.LogInGroupBox();
			this.exportButton = new global::Dox_Tool_V2.LogInButton();
			this.otherInfo = new global::Dox_Tool_V2.LogInRichTextBox();
			this.LogInLabel15 = new global::Dox_Tool_V2.LogInLabel();
			this.emailTemplate = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel14 = new global::Dox_Tool_V2.LogInLabel();
			this.addressTemplate = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel13 = new global::Dox_Tool_V2.LogInLabel();
			this.phoneTemplate = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel12 = new global::Dox_Tool_V2.LogInLabel();
			this.ageTemplate = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel11 = new global::Dox_Tool_V2.LogInLabel();
			this.nameTemplate = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel10 = new global::Dox_Tool_V2.LogInLabel();
			this.LogInGroupBox1 = new global::Dox_Tool_V2.LogInGroupBox();
			this.mapButton = new global::Dox_Tool_V2.LogInButton();
			this.zipCode = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel9 = new global::Dox_Tool_V2.LogInLabel();
			this.latLong = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel8 = new global::Dox_Tool_V2.LogInLabel();
			this.cityState = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel7 = new global::Dox_Tool_V2.LogInLabel();
			this.ipSearchButton = new global::Dox_Tool_V2.LogInButton();
			this.ipText = new global::Dox_Tool_V2.LogInNormalTextBox();
			this.LogInLabel6 = new global::Dox_Tool_V2.LogInLabel();
			this.LogInThemeContainer1.SuspendLayout();
			this.LogInTabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.LogInGroupBox2.SuspendLayout();
			this.LogInGroupBox1.SuspendLayout();
			base.SuspendLayout();
			this.LogInThemeContainer1.AllowClose = true;
			this.LogInThemeContainer1.AllowMaximize = false;
			this.LogInThemeContainer1.AllowMinimize = true;
			this.LogInThemeContainer1.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInThemeContainer1.BaseColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInThemeContainer1.BorderColour = global::System.Drawing.Color.FromArgb(60, 60, 60);
			this.LogInThemeContainer1.ContainerColour = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.LogInThemeContainer1.Controls.Add(this.LogInTabControl1);
			this.LogInThemeContainer1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.LogInThemeContainer1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInThemeContainer1.FontSize = 12;
			this.LogInThemeContainer1.HoverColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInThemeContainer1.Location = new global::System.Drawing.Point(0, 0);
			this.LogInThemeContainer1.Name = "LogInThemeContainer1";
			this.LogInThemeContainer1.ShowIcon = true;
			this.LogInThemeContainer1.Size = new global::System.Drawing.Size(447, 504);
			this.LogInThemeContainer1.TabIndex = 0;
			this.LogInThemeContainer1.Text = "Dox Tool By Drizzy V2";
			this.LogInTabControl1.ActiveColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInTabControl1.BackTabColour = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.LogInTabControl1.BaseColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInTabControl1.BorderColour = global::System.Drawing.Color.FromArgb(30, 30, 30);
			this.LogInTabControl1.Controls.Add(this.TabPage1);
			this.LogInTabControl1.Controls.Add(this.TabPage2);
			this.LogInTabControl1.Controls.Add(this.TabPage3);
			this.LogInTabControl1.Controls.Add(this.TabPage4);
			this.LogInTabControl1.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.LogInTabControl1.HorizontalLineColour = global::System.Drawing.Color.FromArgb(23, 119, 151);
			this.LogInTabControl1.ItemSize = new global::System.Drawing.Size(240, 32);
			this.LogInTabControl1.Location = new global::System.Drawing.Point(3, 34);
			this.LogInTabControl1.Name = "LogInTabControl1";
			this.LogInTabControl1.SelectedIndex = 0;
			this.LogInTabControl1.Size = new global::System.Drawing.Size(443, 467);
			this.LogInTabControl1.TabIndex = 0;
			this.LogInTabControl1.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInTabControl1.UpLineColour = global::System.Drawing.Color.FromArgb(0, 160, 199);
			this.TabPage1.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage1.Controls.Add(this.LogInLabel16);
			this.TabPage1.Controls.Add(this.personProgress);
			this.TabPage1.Controls.Add(this.personSearchResults);
			this.TabPage1.Controls.Add(this.nameSearch);
			this.TabPage1.Controls.Add(this.location);
			this.TabPage1.Controls.Add(this.LogInLabel3);
			this.TabPage1.Controls.Add(this.lastName);
			this.TabPage1.Controls.Add(this.firstName);
			this.TabPage1.Controls.Add(this.LogInLabel2);
			this.TabPage1.Controls.Add(this.LogInLabel1);
			this.TabPage1.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage1.Size = new global::System.Drawing.Size(435, 427);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Person Search";
			this.LogInLabel16.AutoSize = true;
			this.LogInLabel16.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel16.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel16.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel16.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel16.Location = new global::System.Drawing.Point(212, 48);
			this.LogInLabel16.Name = "LogInLabel16";
			this.LogInLabel16.Size = new global::System.Drawing.Size(55, 15);
			this.LogInLabel16.TabIndex = 13;
			this.LogInLabel16.Text = "Progress:";
			this.personProgress.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.personProgress.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.personProgress.FontColour = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.personProgress.Location = new global::System.Drawing.Point(274, 44);
			this.personProgress.Maximum = 100;
			this.personProgress.Name = "personProgress";
			this.personProgress.ProgressColour = global::System.Drawing.Color.FromArgb(0, 160, 199);
			this.personProgress.SecondColour = global::System.Drawing.Color.FromArgb(0, 145, 184);
			this.personProgress.Size = new global::System.Drawing.Size(153, 25);
			this.personProgress.TabIndex = 12;
			this.personProgress.Text = "personProgress";
			this.personProgress.TwoColour = true;
			this.personProgress.Value = 0;
			this.personSearchResults.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.personSearchResults.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.personSearchResults.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.personSearchResults.ForeColor = global::System.Drawing.SystemColors.Info;
			this.personSearchResults.FormattingEnabled = true;
			this.personSearchResults.HorizontalScrollbar = true;
			this.personSearchResults.ItemHeight = 17;
			this.personSearchResults.Location = new global::System.Drawing.Point(9, 112);
			this.personSearchResults.Name = "personSearchResults";
			this.personSearchResults.Size = new global::System.Drawing.Size(418, 289);
			this.personSearchResults.TabIndex = 11;
			this.nameSearch.BackColor = global::System.Drawing.Color.Transparent;
			this.nameSearch.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.nameSearch.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.nameSearch.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.nameSearch.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.nameSearch.Location = new global::System.Drawing.Point(9, 76);
			this.nameSearch.Name = "nameSearch";
			this.nameSearch.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.nameSearch.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.nameSearch.Size = new global::System.Drawing.Size(418, 30);
			this.nameSearch.TabIndex = 8;
			this.nameSearch.Text = "Search";
			this.location.BackColor = global::System.Drawing.Color.Transparent;
			this.location.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.location.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.location.Location = new global::System.Drawing.Point(274, 6);
			this.location.MaxLength = 32767;
			this.location.Multiline = false;
			this.location.Name = "location";
			this.location.ReadOnly = false;
			this.location.Size = new global::System.Drawing.Size(153, 29);
			this.location.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.location.TabIndex = 5;
			this.location.Text = "Zip Code, City, or State";
			this.location.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.location.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.location.UseSystemPasswordChar = false;
			this.LogInLabel3.AutoSize = true;
			this.LogInLabel3.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel3.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel3.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel3.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel3.Location = new global::System.Drawing.Point(212, 13);
			this.LogInLabel3.Name = "LogInLabel3";
			this.LogInLabel3.Size = new global::System.Drawing.Size(56, 15);
			this.LogInLabel3.TabIndex = 4;
			this.LogInLabel3.Text = "Location:";
			this.lastName.BackColor = global::System.Drawing.Color.Transparent;
			this.lastName.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.lastName.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.lastName.Location = new global::System.Drawing.Point(83, 41);
			this.lastName.MaxLength = 32767;
			this.lastName.Multiline = false;
			this.lastName.Name = "lastName";
			this.lastName.ReadOnly = false;
			this.lastName.Size = new global::System.Drawing.Size(117, 29);
			this.lastName.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.lastName.TabIndex = 3;
			this.lastName.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.lastName.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.lastName.UseSystemPasswordChar = false;
			this.firstName.BackColor = global::System.Drawing.Color.Transparent;
			this.firstName.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.firstName.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.firstName.Location = new global::System.Drawing.Point(83, 6);
			this.firstName.MaxLength = 32767;
			this.firstName.Multiline = false;
			this.firstName.Name = "firstName";
			this.firstName.ReadOnly = false;
			this.firstName.Size = new global::System.Drawing.Size(117, 29);
			this.firstName.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.firstName.TabIndex = 2;
			this.firstName.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.firstName.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.firstName.UseSystemPasswordChar = false;
			this.LogInLabel2.AutoSize = true;
			this.LogInLabel2.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel2.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel2.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel2.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel2.Location = new global::System.Drawing.Point(6, 48);
			this.LogInLabel2.Name = "LogInLabel2";
			this.LogInLabel2.Size = new global::System.Drawing.Size(66, 15);
			this.LogInLabel2.TabIndex = 1;
			this.LogInLabel2.Text = "Last Name:";
			this.LogInLabel1.AutoSize = true;
			this.LogInLabel1.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel1.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel1.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel1.Location = new global::System.Drawing.Point(6, 14);
			this.LogInLabel1.Name = "LogInLabel1";
			this.LogInLabel1.Size = new global::System.Drawing.Size(67, 15);
			this.LogInLabel1.TabIndex = 0;
			this.LogInLabel1.Text = "First Name:";
			this.TabPage2.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage2.Controls.Add(this.LogInLabel17);
			this.TabPage2.Controls.Add(this.emailProgress);
			this.TabPage2.Controls.Add(this.emailSearchResults);
			this.TabPage2.Controls.Add(this.emailSearch);
			this.TabPage2.Controls.Add(this.email);
			this.TabPage2.Controls.Add(this.LogInLabel4);
			this.TabPage2.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage2.Size = new global::System.Drawing.Size(435, 427);
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "Email Search";
			this.LogInLabel17.AutoSize = true;
			this.LogInLabel17.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel17.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel17.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel17.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel17.Location = new global::System.Drawing.Point(6, 45);
			this.LogInLabel17.Name = "LogInLabel17";
			this.LogInLabel17.Size = new global::System.Drawing.Size(55, 15);
			this.LogInLabel17.TabIndex = 14;
			this.LogInLabel17.Text = "Progress:";
			this.emailProgress.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.emailProgress.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.emailProgress.FontColour = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.emailProgress.Location = new global::System.Drawing.Point(67, 41);
			this.emailProgress.Maximum = 100;
			this.emailProgress.Name = "emailProgress";
			this.emailProgress.ProgressColour = global::System.Drawing.Color.FromArgb(0, 160, 199);
			this.emailProgress.SecondColour = global::System.Drawing.Color.FromArgb(0, 145, 184);
			this.emailProgress.Size = new global::System.Drawing.Size(360, 25);
			this.emailProgress.TabIndex = 13;
			this.emailProgress.Text = "emailProgress";
			this.emailProgress.TwoColour = true;
			this.emailProgress.Value = 0;
			this.emailSearchResults.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.emailSearchResults.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.emailSearchResults.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.emailSearchResults.ForeColor = global::System.Drawing.SystemColors.Info;
			this.emailSearchResults.FormattingEnabled = true;
			this.emailSearchResults.HorizontalScrollbar = true;
			this.emailSearchResults.ItemHeight = 17;
			this.emailSearchResults.Location = new global::System.Drawing.Point(9, 111);
			this.emailSearchResults.Name = "emailSearchResults";
			this.emailSearchResults.Size = new global::System.Drawing.Size(418, 306);
			this.emailSearchResults.TabIndex = 12;
			this.emailSearch.BackColor = global::System.Drawing.Color.Transparent;
			this.emailSearch.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.emailSearch.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.emailSearch.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.emailSearch.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.emailSearch.Location = new global::System.Drawing.Point(9, 76);
			this.emailSearch.Name = "emailSearch";
			this.emailSearch.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.emailSearch.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.emailSearch.Size = new global::System.Drawing.Size(418, 30);
			this.emailSearch.TabIndex = 2;
			this.emailSearch.Text = "Search";
			this.email.BackColor = global::System.Drawing.Color.Transparent;
			this.email.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.email.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.email.Location = new global::System.Drawing.Point(67, 6);
			this.email.MaxLength = 32767;
			this.email.Multiline = false;
			this.email.Name = "email";
			this.email.ReadOnly = false;
			this.email.Size = new global::System.Drawing.Size(360, 29);
			this.email.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.email.TabIndex = 1;
			this.email.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.email.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.email.UseSystemPasswordChar = false;
			this.LogInLabel4.AutoSize = true;
			this.LogInLabel4.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel4.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel4.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel4.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel4.Location = new global::System.Drawing.Point(6, 13);
			this.LogInLabel4.Name = "LogInLabel4";
			this.LogInLabel4.Size = new global::System.Drawing.Size(39, 15);
			this.LogInLabel4.TabIndex = 0;
			this.LogInLabel4.Text = "Email:";
			this.TabPage3.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage3.Controls.Add(this.LogInLabel18);
			this.TabPage3.Controls.Add(this.usernameProgress);
			this.TabPage3.Controls.Add(this.usernameSearchResults);
			this.TabPage3.Controls.Add(this.userSearch);
			this.TabPage3.Controls.Add(this.usernameSearch);
			this.TabPage3.Controls.Add(this.LogInLabel5);
			this.TabPage3.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Size = new global::System.Drawing.Size(435, 427);
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "Username Search";
			this.LogInLabel18.AutoSize = true;
			this.LogInLabel18.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel18.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel18.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel18.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel18.Location = new global::System.Drawing.Point(6, 46);
			this.LogInLabel18.Name = "LogInLabel18";
			this.LogInLabel18.Size = new global::System.Drawing.Size(55, 15);
			this.LogInLabel18.TabIndex = 16;
			this.LogInLabel18.Text = "Progress:";
			this.usernameProgress.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.usernameProgress.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.usernameProgress.FontColour = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.usernameProgress.Location = new global::System.Drawing.Point(105, 41);
			this.usernameProgress.Maximum = 100;
			this.usernameProgress.Name = "usernameProgress";
			this.usernameProgress.ProgressColour = global::System.Drawing.Color.FromArgb(0, 160, 199);
			this.usernameProgress.SecondColour = global::System.Drawing.Color.FromArgb(0, 145, 184);
			this.usernameProgress.Size = new global::System.Drawing.Size(322, 25);
			this.usernameProgress.TabIndex = 15;
			this.usernameProgress.Text = "LogInProgressBar1";
			this.usernameProgress.TwoColour = true;
			this.usernameProgress.Value = 0;
			this.usernameSearchResults.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.usernameSearchResults.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.usernameSearchResults.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.usernameSearchResults.ForeColor = global::System.Drawing.SystemColors.Info;
			this.usernameSearchResults.FormattingEnabled = true;
			this.usernameSearchResults.HorizontalScrollbar = true;
			this.usernameSearchResults.ItemHeight = 17;
			this.usernameSearchResults.Location = new global::System.Drawing.Point(9, 111);
			this.usernameSearchResults.Name = "usernameSearchResults";
			this.usernameSearchResults.Size = new global::System.Drawing.Size(418, 306);
			this.usernameSearchResults.TabIndex = 13;
			this.userSearch.BackColor = global::System.Drawing.Color.Transparent;
			this.userSearch.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.userSearch.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.userSearch.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.userSearch.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.userSearch.Location = new global::System.Drawing.Point(9, 76);
			this.userSearch.Name = "userSearch";
			this.userSearch.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.userSearch.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.userSearch.Size = new global::System.Drawing.Size(418, 30);
			this.userSearch.TabIndex = 6;
			this.userSearch.Text = "Search";
			this.usernameSearch.BackColor = global::System.Drawing.Color.Transparent;
			this.usernameSearch.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.usernameSearch.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.usernameSearch.Location = new global::System.Drawing.Point(105, 6);
			this.usernameSearch.MaxLength = 32767;
			this.usernameSearch.Multiline = false;
			this.usernameSearch.Name = "usernameSearch";
			this.usernameSearch.ReadOnly = false;
			this.usernameSearch.Size = new global::System.Drawing.Size(322, 29);
			this.usernameSearch.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.usernameSearch.TabIndex = 5;
			this.usernameSearch.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.usernameSearch.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.usernameSearch.UseSystemPasswordChar = false;
			this.LogInLabel5.AutoSize = true;
			this.LogInLabel5.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel5.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel5.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel5.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel5.Location = new global::System.Drawing.Point(6, 14);
			this.LogInLabel5.Name = "LogInLabel5";
			this.LogInLabel5.Size = new global::System.Drawing.Size(93, 15);
			this.LogInLabel5.TabIndex = 4;
			this.LogInLabel5.Text = "Enter Username:";
			this.TabPage4.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage4.Controls.Add(this.LogInGroupBox2);
			this.TabPage4.Controls.Add(this.LogInGroupBox1);
			this.TabPage4.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Size = new global::System.Drawing.Size(435, 427);
			this.TabPage4.TabIndex = 3;
			this.TabPage4.Text = "Extra Tools";
			this.LogInGroupBox2.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox2.Controls.Add(this.exportButton);
			this.LogInGroupBox2.Controls.Add(this.otherInfo);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel15);
			this.LogInGroupBox2.Controls.Add(this.emailTemplate);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel14);
			this.LogInGroupBox2.Controls.Add(this.addressTemplate);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel13);
			this.LogInGroupBox2.Controls.Add(this.phoneTemplate);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel12);
			this.LogInGroupBox2.Controls.Add(this.ageTemplate);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel11);
			this.LogInGroupBox2.Controls.Add(this.nameTemplate);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel10);
			this.LogInGroupBox2.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox2.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox2.Location = new global::System.Drawing.Point(2, 181);
			this.LogInGroupBox2.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox2.Name = "LogInGroupBox2";
			this.LogInGroupBox2.Size = new global::System.Drawing.Size(432, 241);
			this.LogInGroupBox2.TabIndex = 1;
			this.LogInGroupBox2.Text = "Dox Export";
			this.LogInGroupBox2.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.exportButton.BackColor = global::System.Drawing.Color.Transparent;
			this.exportButton.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.exportButton.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.exportButton.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.exportButton.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.exportButton.Location = new global::System.Drawing.Point(9, 208);
			this.exportButton.Name = "exportButton";
			this.exportButton.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.exportButton.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.exportButton.Size = new global::System.Drawing.Size(416, 30);
			this.exportButton.TabIndex = 12;
			this.exportButton.Text = "Export";
			this.otherInfo.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.otherInfo.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.otherInfo.Location = new global::System.Drawing.Point(198, 71);
			this.otherInfo.Name = "otherInfo";
			this.otherInfo.Size = new global::System.Drawing.Size(227, 133);
			this.otherInfo.TabIndex = 11;
			this.otherInfo.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel15.AutoSize = true;
			this.LogInLabel15.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel15.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel15.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel15.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel15.Location = new global::System.Drawing.Point(195, 42);
			this.LogInLabel15.Name = "LogInLabel15";
			this.LogInLabel15.Size = new global::System.Drawing.Size(64, 15);
			this.LogInLabel15.TabIndex = 10;
			this.LogInLabel15.Text = "Other Info:";
			this.emailTemplate.BackColor = global::System.Drawing.Color.Transparent;
			this.emailTemplate.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.emailTemplate.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.emailTemplate.Location = new global::System.Drawing.Point(58, 175);
			this.emailTemplate.MaxLength = 32767;
			this.emailTemplate.Multiline = false;
			this.emailTemplate.Name = "emailTemplate";
			this.emailTemplate.ReadOnly = false;
			this.emailTemplate.Size = new global::System.Drawing.Size(131, 29);
			this.emailTemplate.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.emailTemplate.TabIndex = 9;
			this.emailTemplate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.emailTemplate.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.emailTemplate.UseSystemPasswordChar = false;
			this.LogInLabel14.AutoSize = true;
			this.LogInLabel14.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel14.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel14.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel14.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel14.Location = new global::System.Drawing.Point(6, 183);
			this.LogInLabel14.Name = "LogInLabel14";
			this.LogInLabel14.Size = new global::System.Drawing.Size(39, 15);
			this.LogInLabel14.TabIndex = 8;
			this.LogInLabel14.Text = "Email:";
			this.addressTemplate.BackColor = global::System.Drawing.Color.Transparent;
			this.addressTemplate.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.addressTemplate.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.addressTemplate.Location = new global::System.Drawing.Point(58, 140);
			this.addressTemplate.MaxLength = 32767;
			this.addressTemplate.Multiline = false;
			this.addressTemplate.Name = "addressTemplate";
			this.addressTemplate.ReadOnly = false;
			this.addressTemplate.Size = new global::System.Drawing.Size(131, 29);
			this.addressTemplate.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.addressTemplate.TabIndex = 7;
			this.addressTemplate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.addressTemplate.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.addressTemplate.UseSystemPasswordChar = false;
			this.LogInLabel13.AutoSize = true;
			this.LogInLabel13.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel13.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel13.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel13.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel13.Location = new global::System.Drawing.Point(6, 147);
			this.LogInLabel13.Name = "LogInLabel13";
			this.LogInLabel13.Size = new global::System.Drawing.Size(52, 15);
			this.LogInLabel13.TabIndex = 6;
			this.LogInLabel13.Text = "Address:";
			this.phoneTemplate.BackColor = global::System.Drawing.Color.Transparent;
			this.phoneTemplate.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.phoneTemplate.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.phoneTemplate.Location = new global::System.Drawing.Point(58, 105);
			this.phoneTemplate.MaxLength = 32767;
			this.phoneTemplate.Multiline = false;
			this.phoneTemplate.Name = "phoneTemplate";
			this.phoneTemplate.ReadOnly = false;
			this.phoneTemplate.Size = new global::System.Drawing.Size(131, 29);
			this.phoneTemplate.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.phoneTemplate.TabIndex = 5;
			this.phoneTemplate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.phoneTemplate.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.phoneTemplate.UseSystemPasswordChar = false;
			this.LogInLabel12.AutoSize = true;
			this.LogInLabel12.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel12.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel12.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel12.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel12.Location = new global::System.Drawing.Point(6, 112);
			this.LogInLabel12.Name = "LogInLabel12";
			this.LogInLabel12.Size = new global::System.Drawing.Size(44, 15);
			this.LogInLabel12.TabIndex = 4;
			this.LogInLabel12.Text = "Phone:";
			this.ageTemplate.BackColor = global::System.Drawing.Color.Transparent;
			this.ageTemplate.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.ageTemplate.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ageTemplate.Location = new global::System.Drawing.Point(58, 70);
			this.ageTemplate.MaxLength = 32767;
			this.ageTemplate.Multiline = false;
			this.ageTemplate.Name = "ageTemplate";
			this.ageTemplate.ReadOnly = false;
			this.ageTemplate.Size = new global::System.Drawing.Size(131, 29);
			this.ageTemplate.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.ageTemplate.TabIndex = 3;
			this.ageTemplate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.ageTemplate.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.ageTemplate.UseSystemPasswordChar = false;
			this.LogInLabel11.AutoSize = true;
			this.LogInLabel11.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel11.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel11.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel11.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel11.Location = new global::System.Drawing.Point(6, 77);
			this.LogInLabel11.Name = "LogInLabel11";
			this.LogInLabel11.Size = new global::System.Drawing.Size(31, 15);
			this.LogInLabel11.TabIndex = 2;
			this.LogInLabel11.Text = "Age:";
			this.nameTemplate.BackColor = global::System.Drawing.Color.Transparent;
			this.nameTemplate.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.nameTemplate.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.nameTemplate.Location = new global::System.Drawing.Point(58, 35);
			this.nameTemplate.MaxLength = 32767;
			this.nameTemplate.Multiline = false;
			this.nameTemplate.Name = "nameTemplate";
			this.nameTemplate.ReadOnly = false;
			this.nameTemplate.Size = new global::System.Drawing.Size(131, 29);
			this.nameTemplate.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.nameTemplate.TabIndex = 1;
			this.nameTemplate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.nameTemplate.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.nameTemplate.UseSystemPasswordChar = false;
			this.LogInLabel10.AutoSize = true;
			this.LogInLabel10.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel10.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel10.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel10.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel10.Location = new global::System.Drawing.Point(6, 42);
			this.LogInLabel10.Name = "LogInLabel10";
			this.LogInLabel10.Size = new global::System.Drawing.Size(42, 15);
			this.LogInLabel10.TabIndex = 0;
			this.LogInLabel10.Text = "Name:";
			this.LogInGroupBox1.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox1.Controls.Add(this.mapButton);
			this.LogInGroupBox1.Controls.Add(this.zipCode);
			this.LogInGroupBox1.Controls.Add(this.LogInLabel9);
			this.LogInGroupBox1.Controls.Add(this.latLong);
			this.LogInGroupBox1.Controls.Add(this.LogInLabel8);
			this.LogInGroupBox1.Controls.Add(this.cityState);
			this.LogInGroupBox1.Controls.Add(this.LogInLabel7);
			this.LogInGroupBox1.Controls.Add(this.ipSearchButton);
			this.LogInGroupBox1.Controls.Add(this.ipText);
			this.LogInGroupBox1.Controls.Add(this.LogInLabel6);
			this.LogInGroupBox1.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox1.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox1.Location = new global::System.Drawing.Point(2, 0);
			this.LogInGroupBox1.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox1.Name = "LogInGroupBox1";
			this.LogInGroupBox1.Size = new global::System.Drawing.Size(432, 181);
			this.LogInGroupBox1.TabIndex = 0;
			this.LogInGroupBox1.Text = "IP Tracker";
			this.LogInGroupBox1.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.mapButton.BackColor = global::System.Drawing.Color.Transparent;
			this.mapButton.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.mapButton.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.mapButton.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.mapButton.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.mapButton.Location = new global::System.Drawing.Point(333, 109);
			this.mapButton.Name = "mapButton";
			this.mapButton.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.mapButton.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.mapButton.Size = new global::System.Drawing.Size(94, 29);
			this.mapButton.TabIndex = 10;
			this.mapButton.Text = "Map";
			this.zipCode.BackColor = global::System.Drawing.Color.Transparent;
			this.zipCode.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.zipCode.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.zipCode.Location = new global::System.Drawing.Point(107, 144);
			this.zipCode.MaxLength = 32767;
			this.zipCode.Multiline = false;
			this.zipCode.Name = "zipCode";
			this.zipCode.ReadOnly = false;
			this.zipCode.Size = new global::System.Drawing.Size(221, 29);
			this.zipCode.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.zipCode.TabIndex = 9;
			this.zipCode.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.zipCode.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.zipCode.UseSystemPasswordChar = false;
			this.LogInLabel9.AutoSize = true;
			this.LogInLabel9.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel9.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel9.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel9.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel9.Location = new global::System.Drawing.Point(6, 151);
			this.LogInLabel9.Name = "LogInLabel9";
			this.LogInLabel9.Size = new global::System.Drawing.Size(58, 15);
			this.LogInLabel9.TabIndex = 8;
			this.LogInLabel9.Text = "Zip Code:";
			this.latLong.BackColor = global::System.Drawing.Color.Transparent;
			this.latLong.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.latLong.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.latLong.Location = new global::System.Drawing.Point(107, 109);
			this.latLong.MaxLength = 32767;
			this.latLong.Multiline = false;
			this.latLong.Name = "latLong";
			this.latLong.ReadOnly = false;
			this.latLong.Size = new global::System.Drawing.Size(221, 29);
			this.latLong.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.latLong.TabIndex = 7;
			this.latLong.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.latLong.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.latLong.UseSystemPasswordChar = false;
			this.LogInLabel8.AutoSize = true;
			this.LogInLabel8.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel8.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel8.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel8.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel8.Location = new global::System.Drawing.Point(3, 116);
			this.LogInLabel8.Name = "LogInLabel8";
			this.LogInLabel8.Size = new global::System.Drawing.Size(102, 15);
			this.LogInLabel8.TabIndex = 6;
			this.LogInLabel8.Text = "Approx. Lat/Long:";
			this.cityState.BackColor = global::System.Drawing.Color.Transparent;
			this.cityState.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.cityState.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.cityState.Location = new global::System.Drawing.Point(107, 74);
			this.cityState.MaxLength = 32767;
			this.cityState.Multiline = false;
			this.cityState.Name = "cityState";
			this.cityState.ReadOnly = false;
			this.cityState.Size = new global::System.Drawing.Size(221, 29);
			this.cityState.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.cityState.TabIndex = 5;
			this.cityState.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.cityState.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.cityState.UseSystemPasswordChar = false;
			this.LogInLabel7.AutoSize = true;
			this.LogInLabel7.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel7.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel7.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel7.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel7.Location = new global::System.Drawing.Point(3, 81);
			this.LogInLabel7.Name = "LogInLabel7";
			this.LogInLabel7.Size = new global::System.Drawing.Size(62, 15);
			this.LogInLabel7.TabIndex = 3;
			this.LogInLabel7.Text = "City/State:";
			this.ipSearchButton.BackColor = global::System.Drawing.Color.Transparent;
			this.ipSearchButton.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.ipSearchButton.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.ipSearchButton.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.ipSearchButton.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.ipSearchButton.Location = new global::System.Drawing.Point(333, 36);
			this.ipSearchButton.Name = "ipSearchButton";
			this.ipSearchButton.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.ipSearchButton.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.ipSearchButton.Size = new global::System.Drawing.Size(94, 29);
			this.ipSearchButton.TabIndex = 2;
			this.ipSearchButton.Text = "Search";
			this.ipText.BackColor = global::System.Drawing.Color.Transparent;
			this.ipText.BackgroundColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.ipText.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ipText.Location = new global::System.Drawing.Point(107, 36);
			this.ipText.MaxLength = 32767;
			this.ipText.Multiline = false;
			this.ipText.Name = "ipText";
			this.ipText.ReadOnly = false;
			this.ipText.Size = new global::System.Drawing.Size(221, 29);
			this.ipText.Style = global::Dox_Tool_V2.LogInNormalTextBox.Styles.NotRounded;
			this.ipText.TabIndex = 1;
			this.ipText.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.ipText.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.ipText.UseSystemPasswordChar = false;
			this.LogInLabel6.AutoSize = true;
			this.LogInLabel6.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel6.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel6.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel6.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel6.Location = new global::System.Drawing.Point(3, 43);
			this.LogInLabel6.Name = "LogInLabel6";
			this.LogInLabel6.Size = new global::System.Drawing.Size(95, 15);
			this.LogInLabel6.TabIndex = 0;
			this.LogInLabel6.Text = "Enter IP Address:";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(447, 504);
			base.Controls.Add(this.LogInThemeContainer1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "Form1";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Dox Tool By Drizzy V2";
			base.TransparencyKey = global::System.Drawing.Color.Fuchsia;
			this.LogInThemeContainer1.ResumeLayout(false);
			this.LogInTabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.TabPage3.PerformLayout();
			this.TabPage4.ResumeLayout(false);
			this.LogInGroupBox2.ResumeLayout(false);
			this.LogInGroupBox2.PerformLayout();
			this.LogInGroupBox1.ResumeLayout(false);
			this.LogInGroupBox1.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x0400000E RID: 14
		private global::System.ComponentModel.IContainer components;
	}
}
